FROM n8nio/n8n:1.81.1

# Config padrão
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https
ENV N8N_HOST=0.0.0.0

# Banco de dados (usar PostgreSQL)
ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_HOST=$DB_POSTGRESDB_HOST
ENV DB_POSTGRESDB_PORT=5432
ENV DB_POSTGRESDB_DATABASE=$DB_POSTGRESDB_DATABASE
ENV DB_POSTGRESDB_USER=$DB_POSTGRESDB_USER
ENV DB_POSTGRESDB_PASSWORD=$DB_POSTGRESDB_PASSWORD

EXPOSE 5678

ENTRYPOINT ["tini", "--"]
CMD ["n8n"]
